# Train details
date: "2022-10-01"
time: "00:09"
from: "49584000" # Vrutky
to: "10202003" # Praha

# Tickets details
preffered_class: C1
tariff: 
  - REGULAR
  - CZECH_STUDENT_PASS_26
  - ISIC
  - ISIC

# Notify.run details
notify_code: <code>
