# Train details
date: "2022-07-26"
time: "07:00"
from: "17904003" # Liberec
to: "10202003" # Praha, Černý Most

# Tickets details
preffered_class: False
tariff:
  - REGULAR
  - CZECH_STUDENT_PASS_26
  - ISIC
  - ISIC

# Notify.run details
notify_code: O9HTEuc7wKDKoRWYDFYt
